general:
  dataset_name: ruSentNE_lemmatized #bbc, ruSentNE, ruSentNE_lemmatized, semEval
  batch_size: 16
  device: cpu
  dataloader_shuffle: True
  pretrained_model: bert-base-uncased # bert-base-uncased
  num_classes: 3
  num_workers: 1
  lr: 1e-6
  epochs: 2
  eps: 1e-8
  optimizer: AdamW #Adam, AdamW, SGD
  eval_steps: 10
  logging_steps: 10

preprocessing:
  test_ratio: 0.15
  split: True
  split_ratio: 0.8
  split_seed: 69
  split_shuffle: True
  split_stratify: True
  generate_mapping: True
  save_mapping: True
  tokenizer: BertTokenizerFast # BertTokenizerFast, RobertaTokenizer, GPT2Tokenizer, DistilBertTokenizer, RobertaTokenizerFast
  max_length: 256
  add_special_tokens: True
  pad_to_max_length: True