general:
  dataset_name: ruSentNE #bbc, ruSentNE
  batch_size: 2
  device: cpu:0
  dataloader_shuffle: True
  pretrained_model: bert-base-uncased
  num_classes: 3
  num_workers: 1
  lr: 1e-6
  epochs: 5
  eps: 1e-8
  optimizer: AdamW #Adam, AdamW, SGD
  eval_steps: 500

preprocessing:
  split: True
  split_ratio: 0.8
  split_seed: 42
  split_shuffle: True
  split_stratify: True
  generate_mapping: True
  save_mapping: True
  tokenizer: DistilBertTokenizer # BertTokenizerFast, RobertaTokenizer, GPT2Tokenizer, DistilBertTokenizer
  max_length: 256
  add_special_tokens: True
  pad_to_max_length: True